In [1]:
import numpy

In [2]:
import numpy as np

In [3]:
a=[1,2,3,4,5,6]
b=np.array(a)
print(b)

[1 2 3 4 5 6]


In [4]:
print(type(b))

<class 'numpy.ndarray'>


## creating Numpy array from a list

In [5]:
a=np.array([[1,3,6,9],[1,9,6,2]])
print(a)

[[1 3 6 9]
 [1 9 6 2]]


In [6]:
np.array((1,3,5,6))

array([1, 3, 5, 6])

# print dimension


In [7]:
a.ndim

2

# shape

In [8]:
a.shape

(2, 4)

In [9]:
b=np.array([[1,2,3,6,5],[5,9,8,7]])
print(b)

[list([1, 2, 3, 6, 5]) list([5, 9, 8, 7])]


C:\Users\deepp\AppData\Local\Temp/ipykernel_16176/4120435293.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  b=np.array([[1,2,3,6,5],[5,9,8,7]])


In [10]:
b.ndim

1

In [11]:
b.shape

(2,)

In [12]:
g=np.array([[1,2,3,6],[2,9,8,4]])
print(g)

[[1 2 3 6]
 [2 9 8 4]]


In [13]:
g.ndim

2

In [14]:
g.shape

(2, 4)

In [15]:
k=np.array([[2,5,9,8],[5,9,63,3]])

In [16]:
(k)

array([[ 2,  5,  9,  8],
       [ 5,  9, 63,  3]])

In [17]:
k.ndim

2

In [18]:
k.shape

(2, 4)

In [19]:
matrix=[[2,3,4],[5,6,7],[8,9,10]]
b=np.array(matrix)
print(b)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [20]:
b.ndim

2

In [21]:
b.shape

(3, 3)

## function for creating array

# arange= is an array value version of built in python range function 

# syntax= np.arange(start,end,step)

In [22]:
np.arange(10,100,10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

# linspace= return evenly spaced no. over a specific interval

# syntax:- np.linspace(start,end,no of sample)

In [23]:
np.linspace(0,20,3)

array([ 0., 10., 20.])

In [24]:

np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

# zeros:- generate array of zeros

# syntax:- np.zeros(shape)

In [25]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
b=np.array([[1,2,3,6],[2,2,8,9],[8,9,2,1]])
print(b)

[[1 2 3 6]
 [2 2 8 9]
 [8 9 2 1]]


In [27]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

## random.randint

# returns randon integers start to end

# syntax:- np.random.randint(star,end,no of sample)

In [28]:
a=np.random.randint(1,20,5)
print(a)

[15 14  5  7 16]


In [29]:
np.random.randint(1,40,10)

array([21, 32,  7,  4, 15, 14, 37, 27,  7, 13])

## OPERATIONS

## Flattening:- it is used to convert n-dimension array to 1-dimension array

# and the function name is **ravel**

In [30]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# ravel function convert nd array to 1d array

In [31]:
b=np.array([[5,6,9],[6,8,5]])
c=b.ravel()
print(c)

[5 6 9 6 8 5]


# reshape array

In [32]:
a=np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [33]:
a.shape

(20,)

In [34]:
b=a.reshape(4,5)
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [35]:
a=np.arange(25)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [36]:
k=np.arange(20)
print(k)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [37]:
c=np.arange(20)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [38]:
c.shape

(20,)

In [39]:
c.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
c.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [41]:
a=np.array([[1,3,6],[8,9,7]])
print(a)

[[1 3 6]
 [8 9 7]]


In [42]:
b=a.reshape(3,2)
print(b)

[[1 3]
 [6 8]
 [9 7]]


In [43]:
b=a.reshape(2,3)
print(b)

[[1 3 6]
 [8 9 7]]


In [44]:
b=a.reshape(1,6)
print(b)

[[1 3 6 8 9 7]]


In [45]:
print(a)

[[1 3 6]
 [8 9 7]]


In [46]:
c=a.T
print(c)

[[1 8]
 [3 9]
 [6 7]]


In [47]:
np.array(a)

array([[1, 3, 6],
       [8, 9, 7]])

## transpose array

In [48]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**reshape :- works on ravel+row wise addition**

In [50]:
a.shape

(3, 3)

In [51]:
a.ndim

2

In [52]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

## copy Array

In [53]:
a=np.array([1,2,3]) # shallow copy
b=a
b[0]=100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [54]:
a=np.array([4,5,6])
b=a.copy()
b[1]=50
print(a)
print(b)

[4 5 6]
[ 4 50  6]


## sort

In [55]:
np.sort([5,89,47,65,461])

array([  5,  47,  65,  89, 461])

In [56]:
a=np.array([[30,20,10],[60,50,40]])
b=np.sort(a)
print(b)

[[10 20 30]
 [40 50 60]]


In [57]:
c=np.sort(a,axis=1) #sorting along an axis
print(c)

[[10 20 30]
 [40 50 60]]


In [58]:
d=np.sort(a,axis=0)
print(d)

[[30 20 10]
 [60 50 40]]


In [59]:
e=np.array([[9,8,7],[6,5,4],[10,9,18]])
f=np.sort(e,axis=1)
print(f)

[[ 7  8  9]
 [ 4  5  6]
 [ 9 10 18]]


In [60]:
np.sort(e,axis=0)

array([[ 6,  5,  4],
       [ 9,  8,  7],
       [10,  9, 18]])

## Add/Remove operation on numpy array

In [61]:
a=np.array([5,9,8,7])
a=np.append(a,[3,2,1])
print(a)

[5 9 8 7 3 2 1]


# delete:- fuction works on index wise
# remove:- function works on value wise

In [62]:
a=np.delete(a,2)
print(a)

[5 9 7 3 2 1]


In [63]:
np.delete(a,0)

array([9, 7, 3, 2, 1])

## indexing

In [64]:
a=np.arange(3,15)
print(a)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [65]:
print(a[7])

10


In [66]:
a[5]=50
print(a)

[ 3  4  5  6  7 50  9 10 11 12 13 14]


## diagonal matrix

In [67]:
d=np.diag([7,8,9])

print(d)

[[7 0 0]
 [0 8 0]
 [0 0 9]]


In [68]:
print(d[1,0])

0


In [69]:
d[2,1]=50
print(d)

[[ 7  0  0]
 [ 0  8  0]
 [ 0 50  9]]


## indexing with an array of integers

In [70]:
a=np.arange(0,101,10)
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

**indexing can be done with an array of integer**

In [71]:
b=a[[4,8,7]] 
print(b)

[40 80 70]


**new value can be assigned to be multiple variable**

In [72]:
a[[2,7,10]]=15
print(a)

[ 0 10 15 30 40 50 60 15 80 90 15]


## mask indexing or fancy indexing

In [73]:
a=np.array([16,15,6,8,9,10,18])
print(a)

[16 15  6  8  9 10 18]


In [74]:
a%2==0

array([ True, False,  True,  True, False,  True,  True])

In [75]:
a[a%2==0]

array([16,  6,  8, 10, 18])

In [76]:
a[a%2!=0]

array([15,  9])

## slicing

In [77]:
a=np.arange(4,20)
print(a)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [78]:
a[1:10:2]

array([ 5,  7,  9, 11, 13])

# arithmetic operation

In [79]:
a=np.array([1,5,9,8,89,54])
print(a)

[ 1  5  9  8 89 54]


In [80]:
print(a+2)

[ 3  7 11 10 91 56]


In [81]:
a**2

array([   1,   25,   81,   64, 7921, 2916], dtype=int32)

In [82]:
    l=[1,2,3,4]
    
    for i in range(len(l)):
        l[i]=l[i]+1
        
    print(l)

[2, 3, 4, 5]


In [83]:
b=np.ones(4)+3
print(b)

[4. 4. 4. 4.]


In [84]:
a=np.array([1,6,9,8,])
print(a)

[1 6 9 8]


In [85]:
a+b

array([ 5., 10., 13., 12.])

In [86]:
a*b

array([ 4., 24., 36., 32.])

In [87]:
c=np.ones(5)
print(c)

[1. 1. 1. 1. 1.]


In [88]:
d=c+5
print(d)

[6. 6. 6. 6. 6.]


In [89]:
a=np.array([[1,2],[3,4],[5,6]]) 

b=np.array([[7,8],[9,10],[1,2]])



In [90]:
print(a+b)

[[ 8 10]
 [12 14]
 [ 6  8]]


In [91]:
print(a*b)

[[ 7 16]
 [27 40]
 [ 5 12]]


In [93]:
np.matmul(a,b)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

# matrix multiplication

In [94]:
a=np.array([[1,2,6],[3,4,8],[5,6,1]])
b=np.array([[2,3,3],[4,5,9],[6,8,9]])
np.matmul(a,b)

array([[ 46,  61,  75],
       [ 70,  93, 117],
       [ 40,  53,  78]])

In [95]:
print(a)

print(b)

[[1 2 6]
 [3 4 8]
 [5 6 1]]
[[2 3 3]
 [4 5 9]
 [6 8 9]]


In [96]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[4,8]])

np.matmul(a,b)

array([[13, 22],
       [31, 50]])